name: Check Pull Request
on:
    pull_request: {}
jobs:
    validate:
        strategy:
            matrix:
                node: [12, 14, 15]
        runs-on: ubuntu-latest
        steps:
            - name: 🛑 Cancel Previous Runs
              uses: styfle/cancel-workflow-action@0.6.0
              with:
                  access_token: ${{ secrets.GITHUB_TOKEN }}

            - name: ⬇️ Checkout repo
              uses: actions/checkout@v2

            - name: ⎔ Setup node
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node }}

            - name: 📥 Install dependencies
              run: yarn bootstrap
              env:
                  HUSKY_SKIP_INSTALL: true

            - name: ▶️ Run validate script
              run: yarn validate

            - name: ⬆️ Upload coverage report
              uses: codecov/codecov-action@v1
